### ISSUE TITLE
Pypi Support 

### ISSUE THREAD

**Issue by oscarmcm** [lockwooddev/django-perseus#1]
Hey, this lib is available in Pypi? I encountered this https://pypi.python.org/pypi/django-perseus/0.1.0 but Pypi could not find any downloads that satisfy the requirement django-perseus==0.1.0

**Comment by lockwooddev** [comment]
It should be available on pypi. I checked it and I encountered the same issue as you did. My apologies, I will look into it as soon as I can!

**Comment by lockwooddev** [comment]
For some reason the package was not uploaded to pypi. It should be there now. Let me know if it works and what you think about it :)

**Comment by oscarmcm** [comment]
Woohoo!, I tested today and now it's available for download, thanks for all :+1:

**Comment by lockwooddev** [comment]
No problem :+1: Thanks for letting me know it was broken!
