### ISSUE TITLE
Zip Option

### ISSUE THREAD

**Issue by oscarmcm** [lockwooddev/django-perseus#2]
Hey when I run django-perseus from the command line and pass --archive true foo.zip this not run, I think that this is simple bug and you need update your code , btw I forked this repository and edited render.py  this form work for me

```
class Command(BaseCommand):

    option_list = BaseCommand.option_list + (make_option(
        '--archive',
        action='store_true',
        dest='archive',
        default=False,
        help='Zips the result of the statically generated website'),
        make_option('--filename',
        action='store',
        dest='filename',
        default=''),
    )

    def handle(self, *args, **options):
        run_renderers()
        run_importers()

        if options['archive']:
            zip_dir(options.get('filename', 'render.zip'))
```

**Comment by oscarmcm** [comment]
I Open a [PR](https://github.com/lockwooddev/django-perseus/pull/3) that solve this issue

**Comment by lockwooddev** [comment]
Thanks for reporting this. I took the freedom of changing your PR slightly and added few test cases to test the new functionality. [PR](https://github.com/lockwooddev/django-perseus/pull/4)

This works for you now?

**Comment by oscarmcm** [comment]
yeah, the zip function now work, thanks for accept the [PR](https://github.com/lockwooddev/django-perseus/pull/4) :+1:
